# Generated by Django 6.0.2 on 2026-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothing', 'Clothing'), ('accessories', 'Accessories')], default='shoes', max_length=20),
        ),
    ]
