# Generated by Django 6.0.2 on 2026-02-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('lifestyle', 'Lifestyle'), ('jordan', 'Jordan'), ('running', 'Running'), ('football', 'Football'), ('basketball', 'Basketball'), ('training-gym', 'Training and Gym'), ('skateboarding', 'Skateboarding'), ('custom-shoes', 'Custom Shoes'), ('hoodies-sweatshirts', 'Hoodies and Sweatshirts'), ('trousers-tights', 'Trousers and Tights'), ('tracksuits', 'Tracksuits'), ('jackets', 'Jackets'), ('tops-tshirts', 'Tops and T-Shirts'), ('shorts', 'Shorts')], max_length=30),
        ),
    ]
