/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeIndexRouteImport } from './routes/$type/index'
import { Route as TypeProductIdRouteImport } from './routes/$type/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeIndexRoute = TypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeProductIdRoute = TypeProductIdRouteImport.update({
  id: '/$type/$productId',
  path: '/$type/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$type/$productId': typeof TypeProductIdRoute
  '/$type/': typeof TypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$type/$productId': typeof TypeProductIdRoute
  '/$type': typeof TypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$type/$productId': typeof TypeProductIdRoute
  '/$type/': typeof TypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$type/$productId' | '/$type/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$type/$productId' | '/$type'
  id: '__root__' | '/' | '/$type/$productId' | '/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TypeProductIdRoute: typeof TypeProductIdRoute
  TypeIndexRoute: typeof TypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/': {
      id: '/$type/'
      path: '/$type'
      fullPath: '/$type/'
      preLoaderRoute: typeof TypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/$productId': {
      id: '/$type/$productId'
      path: '/$type/$productId'
      fullPath: '/$type/$productId'
      preLoaderRoute: typeof TypeProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TypeProductIdRoute: TypeProductIdRoute,
  TypeIndexRoute: TypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
